import { Theme } from '../types/index.js';

const defaultBarStyle = {
  fgColor: '#4caf50',
  bgColor: '[#000000]',
  animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
};

export const builtInThemes: Record<string, Theme> = {
  default: {
    name: 'default',
    colors: {
      model: '#00bcd4',
      label: '#757575',
      warning: '#ff9800',
      error: '#f44336',
      dim: '#757575',
      toolActive: '#ff9800',
      toolDone: '#4caf50',
      agentRunning: '#00bcd4',
      todoPending: '#ff9800',
      todoDone: '#4caf50',
      cost: '#e91e63',
      gitBranch: '#2196f3',
      gitDirty: '#ff9800',
    },
    bars: {
      context: { ...defaultBarStyle },
      quota5h: { ...defaultBarStyle, fgColor: '#ff9800' },
      quota24h: { ...defaultBarStyle, fgColor: '#2196f3' },
      quota7d: { ...defaultBarStyle, fgColor: '#e91e63' },
      quota30d: { ...defaultBarStyle, fgColor: '#00bcd4' },
      quotaWeekly: { ...defaultBarStyle, fgColor: '#9c27b0' },
    },
    icons: {
      deepseek: '🔥',
      kimi: '🌙',
      glm: '🧠',
      minimax: '🎭',
      mimo: '📱',
      warning: '⚠️',
      error: '🔴',
      tool: '🔧',
      agent: '🤖',
      todo: '📝',
      gitBranch: '⎇',
      gitDirty: '*',
    },
    layout: { compact: false, showLabels: true, barWidth: 10 },
  },
  minimal: {
    name: 'minimal',
    colors: {
      model: '#e5e5e5',
      label: '#e5e5e5',
      warning: '#e5e5e5',
      error: '#e5e5e5',
      dim: '#e5e5e5',
      toolActive: '#e5e5e5',
      toolDone: '#e5e5e5',
      agentRunning: '#e5e5e5',
      todoPending: '#e5e5e5',
      todoDone: '#e5e5e5',
      cost: '#e5e5e5',
      gitBranch: '#e5e5e5',
      gitDirty: '#e5e5e5',
    },
    bars: {
      context: {
        fgColor: '#e5e5e5',
        bgColor: '[#000000]',
        animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
      },
      quota5h: {
        fgColor: '#e5e5e5',
        bgColor: '[#000000]',
        animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
      },
      quota24h: {
        fgColor: '#e5e5e5',
        bgColor: '[#000000]',
        animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
      },
      quota7d: {
        fgColor: '#e5e5e5',
        bgColor: '[#000000]',
        animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
      },
      quota30d: {
        fgColor: '#e5e5e5',
        bgColor: '[#000000]',
        animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
      },
      quotaWeekly: {
        fgColor: '#e5e5e5',
        bgColor: '[#000000]',
        animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
      },
    },
    icons: {
      warning: '!',
      error: 'X',
      tool: '',
      agent: '',
      todo: '',
      gitBranch: '',
      gitDirty: '*',
    },
    layout: { compact: true, showLabels: false, barWidth: 10 },
  },
  powerline: {
    name: 'powerline',
    colors: {
      model: '#ffffff',
      label: '#757575',
      warning: '#000000',
      error: '#ffffff',
      dim: '#757575',
      toolActive: '#ff9800',
      toolDone: '#4caf50',
      agentRunning: '#00bcd4',
      todoPending: '#ff9800',
      todoDone: '#4caf50',
      cost: '#e91e63',
      gitBranch: '#2196f3',
      gitDirty: '#ff9800',
    },
    bars: {
      context: { ...defaultBarStyle },
      quota5h: { ...defaultBarStyle, fgColor: '#ff9800' },
      quota24h: { ...defaultBarStyle, fgColor: '#2196f3' },
      quota7d: { ...defaultBarStyle, fgColor: '#e91e63' },
      quota30d: { ...defaultBarStyle, fgColor: '#00bcd4' },
      quotaWeekly: { ...defaultBarStyle, fgColor: '#9c27b0' },
    },
    icons: {
      deepseek: 'DS',
      kimi: 'KM',
      glm: 'GL',
      minimax: 'MX',
      mimo: 'MI',
      warning: '▲',
      error: '✖',
      tool: '●',
      agent: '◎',
      todo: '○',
      gitBranch: '⎇',
      gitDirty: '●',
    },
    layout: { compact: false, showLabels: true, barWidth: 10 },
  },
  neon: {
    name: 'neon',
    colors: {
      model: '#e040fb',
      label: '#757575',
      warning: '#ffd740',
      error: '#ff5252',
      dim: '#757575',
      toolActive: '#ffd740',
      toolDone: '#69f0ae',
      agentRunning: '#29b8db',
      todoPending: '#ffd740',
      todoDone: '#69f0ae',
      cost: '#e040fb',
      gitBranch: '#448aff',
      gitDirty: '#ffd740',
    },
    bars: {
      context: {
        fgColor: '#69f0ae',
        bgColor: '[#000000]',
        animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
      },
      quota5h: {
        fgColor: '#ffd740',
        bgColor: '[#000000]',
        animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
      },
      quota24h: {
        fgColor: '#448aff',
        bgColor: '[#000000]',
        animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
      },
      quota7d: {
        fgColor: '#e040fb',
        bgColor: '[#000000]',
        animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
      },
      quota30d: {
        fgColor: '#29b8db',
        bgColor: '[#000000]',
        animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
      },
      quotaWeekly: {
        fgColor: '#ea80fc',
        bgColor: '[#000000]',
        animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
      },
    },
    icons: {
      deepseek: '🔥',
      kimi: '🌙',
      glm: '🧠',
      minimax: '🎭',
      mimo: '📱',
      warning: '⚡',
      error: '💥',
      tool: '🔧',
      agent: '🤖',
      todo: '📝',
      gitBranch: '⎇',
      gitDirty: '✨',
    },
    layout: { compact: false, showLabels: true, barWidth: 12 },
  },
};
