import { Theme } from '../types/index.js';

const defaultBarStyle = {
  fgColor: '[32m',
  bgColor: '[40m',
  animation: { enabled: false, mode: 'on-change' as const, type: 'none' as const, triggerThreshold: 5 },
};

export const builtInThemes: Record<string, Theme> = {
  default: {
    name: 'default',
    colors: {
      model: '[36m',
      label: '[90m',
      warning: '[33m',
      error: '[31m',
      dim: '[90m',
      toolActive: '[33m',
      toolDone: '[32m',
      agentRunning: '[36m',
      todoPending: '[33m',
      todoDone: '[32m',
      cost: '[35m',
      gitBranch: '[34m',
      gitDirty: '[33m',
    },
    bars: {
      context: { ...defaultBarStyle },
      quota5h: { ...defaultBarStyle, fgColor: '[33m' },
      quota24h: { ...defaultBarStyle, fgColor: '[34m' },
      quota7d: { ...defaultBarStyle, fgColor: '[35m' },
      quota30d: { ...defaultBarStyle, fgColor: '[36m' },
    },
    icons: {
      deepseek: '🔥',
      kimi: '🌙',
      glm: '🧠',
      minimax: '🎭',
      warning: '⚠️',
      error: '🔴',
      tool: '🔧',
      agent: '🤖',
      todo: '📝',
      gitBranch: '⎇',
      gitDirty: '*',
    },
    layout: { compact: false, showLabels: true, barWidth: 10 },
  },
  minimal: {
    name: 'minimal',
    colors: {
      model: '[0m',
      label: '[0m',
      warning: '[0m',
      error: '[0m',
      dim: '[0m',
      toolActive: '[0m',
      toolDone: '[0m',
      agentRunning: '[0m',
      todoPending: '[0m',
      todoDone: '[0m',
      cost: '[0m',
      gitBranch: '[0m',
      gitDirty: '[0m',
    },
    bars: {
      context: { ...defaultBarStyle, fgColor: '[0m', bgColor: '[0m' },
      quota5h: { ...defaultBarStyle, fgColor: '[0m', bgColor: '[0m' },
      quota24h: { ...defaultBarStyle, fgColor: '[0m', bgColor: '[0m' },
      quota7d: { ...defaultBarStyle, fgColor: '[0m', bgColor: '[0m' },
      quota30d: { ...defaultBarStyle, fgColor: '[0m', bgColor: '[0m' },
    },
    icons: {
      warning: '!',
      error: 'X',
      tool: '',
      agent: '',
      todo: '',
      gitBranch: '',
      gitDirty: '*',
    },
    layout: { compact: true, showLabels: false, barWidth: 10 },
  },
  powerline: {
    name: 'powerline',
    colors: {
      model: '[97;44m',
      label: '[90m',
      warning: '[30;43m',
      error: '[97;41m',
      dim: '[90m',
      toolActive: '[33m',
      toolDone: '[32m',
      agentRunning: '[36m',
      todoPending: '[33m',
      todoDone: '[32m',
      cost: '[35m',
      gitBranch: '[34m',
      gitDirty: '[33m',
    },
    bars: {
      context: { ...defaultBarStyle },
      quota5h: { ...defaultBarStyle, fgColor: '[33m' },
      quota24h: { ...defaultBarStyle, fgColor: '[34m' },
      quota7d: { ...defaultBarStyle, fgColor: '[35m' },
      quota30d: { ...defaultBarStyle, fgColor: '[36m' },
    },
    icons: {
      deepseek: 'DS',
      kimi: 'KM',
      glm: 'GL',
      minimax: 'MX',
      warning: '▲',
      error: '✖',
      tool: '●',
      agent: '◎',
      todo: '○',
      gitBranch: '⎇',
      gitDirty: '●',
    },
    layout: { compact: false, showLabels: true, barWidth: 10 },
  },
  neon: {
    name: 'neon',
    colors: {
      model: '[95m',
      label: '[90m',
      warning: '[93m',
      error: '[91m',
      dim: '[90m',
      toolActive: '[93m',
      toolDone: '[92m',
      agentRunning: '[96m',
      todoPending: '[93m',
      todoDone: '[92m',
      cost: '[95m',
      gitBranch: '[94m',
      gitDirty: '[93m',
    },
    bars: {
      context: { ...defaultBarStyle, fgColor: '[92m', bgColor: '[40m' },
      quota5h: { ...defaultBarStyle, fgColor: '[93m', bgColor: '[40m' },
      quota24h: { ...defaultBarStyle, fgColor: '[94m', bgColor: '[40m' },
      quota7d: { ...defaultBarStyle, fgColor: '[95m', bgColor: '[40m' },
      quota30d: { ...defaultBarStyle, fgColor: '[96m', bgColor: '[40m' },
    },
    icons: {
      deepseek: '🔥',
      kimi: '🌙',
      glm: '🧠',
      minimax: '🎭',
      warning: '⚡',
      error: '💥',
      tool: '🔧',
      agent: '🤖',
      todo: '📝',
      gitBranch: '⎇',
      gitDirty: '✨',
    },
    layout: { compact: false, showLabels: true, barWidth: 12 },
  },
};
